### ISSUE TITLE
Problem with Hide tab bar with one tab add-on

### ISSUE THREAD

**Issue by mozo78** [Lootyhoof/noiamoon#2]
Hello, thank you for the great work with Noia Moon! 
Since Pale Moon 28.0.0 the good old Noia 1.8.9 isn't compatible with the browser anymore and yesterday I installed Noia Moon. All went great but I noticed a problem - there is a color differencies with "Hide tab bar with one tab" add-on. When there aren't any opened tabs, the color scheme is lighter. When open second tab, the colors goes darker until all tabs are closed. If I disable this addon the problem disappears. 

Colour scheme without opened tabs:
![1](https://user-images.githubusercontent.com/38666396/44299278-92e87900-a2fb-11e8-935d-05cfc97f2fc8.png)
Colour scheme with one or more opened tabs:
![2](https://user-images.githubusercontent.com/38666396/44299283-a4318580-a2fb-11e8-8da8-1202ed93c3f2.png)

The problem occurs only if the Gray theme (the first colour option in Noia Moon Options menu) is chosen. Can you please fix this?

**Comment by Lootyhoof** [comment]
This looks to be an intentional effect from what I can see - if you make the tab bar transparent in the options the rest of that background is shown even when the tab bar is enabled.

Also, unrelated to the issue: It's not necessary to use that add-on - you could use this preference instead:

![Tab bar](https://i.imgur.com/xnltsBX.png)

**Comment by mozo78** [comment]
Thank you very much for the answer :)
I now uninstalled the add-on and already use the builtin preference :)
Despite this behaviour is intentional, can you do something about it? There isn't such effect with Noia and for me it's very annoyng.

**Comment by Lootyhoof** [comment]
There isn't, nor would I want to add such a thing. As an example, it's shown constantly for those with tabs on top:

![Tabs on top](https://i.imgur.com/Z20tE8W.png)

The effect is applied to the entire toolbox area, which is how it's able to stretch across the toolbars accordingly.
