### ISSUE TITLE
applying theme to Firefox

### ISSUE THREAD

**Issue by 55trucker** [Lootyhoof/noiamoon#4]
Looty:

how would I go about applying your work here to Firefox 128?

seeing as I have your entire project, opened up into the separate folders

if one were to come in thru the chrome.css route how difficult will it be to apply all of the contents of the Noia theme?

thx

**Comment by Lootyhoof** [comment]
Not possible, sorry. Aside from the method of applying the theme (which is quite different compared to an XUL theme) this just isn't compatible with current Firefox versions, sorry. You should use Pale Moon if you want to use this theme.

**Comment by 55trucker** [comment]
I am using Pale Moon, the latest, I am constantly running into issues where webpage developers don't recognize Pale Moon as a valid web browser, (the worst one being my online banking provider & the countries government webserver). This is getting worse & the only cure for this is to *do what the web service advises* ...use a valid browser.

**Comment by Lootyhoof** [comment]
Sorry, but if you use Firefox, you're limited to what that browser provides. It's a different experience.

**Comment by 55trucker** [comment]
Not your fault, the Noia theme has been my go-to for 16 years, from the time I 1st applied it to Firefox back then, 
to when Firefox deviated from the open source platform & Noia 4 would no longer function I went to Pale Moon as the theme still worked & then to your work when Noia 4 1.8.9 no longer was supported.

**Comment by 55trucker** [comment]
Before I sign off on this possible project are there any small portions of your script that I might be able enter into a Firefox userChrome file to make some cosmetic changes?

the *royal blue* semi-transparent color of the tabs, the right side scrollbar design & the *royal blue* shade, the drop down menus that display a left side gradient margin?
I remember all of your browser work that you did years ago for Firefox before they went in another direction making it difficult to keep up with the platform changes when trying to develop themes.

thx
![Pale moon screenshot](https://github.com/user-attachments/assets/c04061e0-e13b-402b-b416-a51f2800107a)

**Comment by Lootyhoof** [comment]
Not really, sorry. Things have changed considerably in the last few years and there would need to be a lot of work done to make it look anything decent.

**Comment by 55trucker** [comment]
Yeah, I agree with your there, Firefox is a bland looking browser.
